# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/devnix/dev/qtVideoplayer/Qt/videoplayer.ui'
#
# Created: Thu Jan  3 10:33:04 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 567)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoDestination = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoDestination.sizePolicy().hasHeightForWidth())
        self.videoDestination.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 106, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 106, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 106, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.videoDestination.setPalette(palette)
        self.videoDestination.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.videoDestination.setAutoFillBackground(True)
        self.videoDestination.setFrameShape(QtGui.QFrame.StyledPanel)
        self.videoDestination.setFrameShadow(QtGui.QFrame.Raised)
        self.videoDestination.setObjectName("videoDestination")
        self.verticalLayout.addWidget(self.videoDestination)
        self.gridLayout.addLayout(self.verticalLayout, 0, 12, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPlayPause = QtGui.QPushButton(self.centralwidget)
        self.btnPlayPause.setMaximumSize(QtCore.QSize(24, 24))
        self.btnPlayPause.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playback-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnPlayPause.setIcon(icon)
        self.btnPlayPause.setCheckable(True)
        self.btnPlayPause.setObjectName("btnPlayPause")
        self.horizontalLayout.addWidget(self.btnPlayPause)
        self.btnStop = QtGui.QPushButton(self.centralwidget)
        self.btnStop.setMaximumSize(QtCore.QSize(24, 24))
        self.btnStop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon1)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.sldSeek = phonon.Phonon.SeekSlider(self.centralwidget)
        self.sldSeek.setEnabled(True)
        self.sldSeek.setMaximumSize(QtCore.QSize(16777215, 24))
        self.sldSeek.setMouseTracking(False)
        self.sldSeek.setObjectName("sldSeek")
        self.horizontalLayout.addWidget(self.sldSeek)
        self.btnPrevious = QtGui.QPushButton(self.centralwidget)
        self.btnPrevious.setMaximumSize(QtCore.QSize(24, 24))
        self.btnPrevious.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-skip-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrevious.setIcon(icon2)
        self.btnPrevious.setObjectName("btnPrevious")
        self.horizontalLayout.addWidget(self.btnPrevious)
        self.sldVolume = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.sldVolume.setMaximumSize(QtCore.QSize(100, 24))
        self.sldVolume.setObjectName("sldVolume")
        self.horizontalLayout.addWidget(self.sldVolume)
        self.btnNext = QtGui.QPushButton(self.centralwidget)
        self.btnNext.setMaximumSize(QtCore.QSize(24, 24))
        self.btnNext.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-skip-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon3)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout.addWidget(self.btnNext)
        self.btnFullscreen = QtGui.QPushButton(self.centralwidget)
        self.btnFullscreen.setMaximumSize(QtCore.QSize(24, 24))
        self.btnFullscreen.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Buttons/icons/view-fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFullscreen.setIcon(icon4)
        self.btnFullscreen.setObjectName("btnFullscreen")
        self.horizontalLayout.addWidget(self.btnFullscreen)
        self.cbxVideoAspect = QtGui.QComboBox(self.centralwidget)
        self.cbxVideoAspect.setMaximumSize(QtCore.QSize(16777215, 24))
        self.cbxVideoAspect.setObjectName("cbxVideoAspect")
        self.cbxVideoAspect.addItem("")
        self.cbxVideoAspect.addItem("")
        self.horizontalLayout.addWidget(self.cbxVideoAspect)
        self.btnAbout = QtGui.QPushButton(self.centralwidget)
        self.btnAbout.setMaximumSize(QtCore.QSize(24, 24))
        self.btnAbout.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Buttons/icons/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAbout.setIcon(icon5)
        self.btnAbout.setObjectName("btnAbout")
        self.horizontalLayout.addWidget(self.btnAbout)
        self.lblTime = QtGui.QLabel(self.centralwidget)
        self.lblTime.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lblTime.setTextFormat(QtCore.Qt.LogText)
        self.lblTime.setObjectName("lblTime")
        self.horizontalLayout.addWidget(self.lblTime)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 12, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_3.setEnabled(True)
        self.dockWidget_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dockWidget_3.setFloating(False)
        self.dockWidget_3.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnShufflePlayList = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnShufflePlayList.setMaximumSize(QtCore.QSize(24, 24))
        self.btnShufflePlayList.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playlist-shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShufflePlayList.setIcon(icon6)
        self.btnShufflePlayList.setObjectName("btnShufflePlayList")
        self.gridLayout_2.addWidget(self.btnShufflePlayList, 1, 2, 1, 1)
        self.btnClearPlayList = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnClearPlayList.setMaximumSize(QtCore.QSize(24, 24))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Buttons/icons/edit-clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClearPlayList.setIcon(icon7)
        self.btnClearPlayList.setObjectName("btnClearPlayList")
        self.gridLayout_2.addWidget(self.btnClearPlayList, 1, 6, 1, 1)
        self.btnRemoveMedia = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnRemoveMedia.setMaximumSize(QtCore.QSize(24, 24))
        self.btnRemoveMedia.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Buttons/icons/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemoveMedia.setIcon(icon8)
        self.btnRemoveMedia.setObjectName("btnRemoveMedia")
        self.gridLayout_2.addWidget(self.btnRemoveMedia, 1, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.btnAddMedia = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnAddMedia.setMaximumSize(QtCore.QSize(24, 24))
        self.btnAddMedia.setStyleSheet("")
        self.btnAddMedia.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Buttons/icons/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddMedia.setIcon(icon9)
        self.btnAddMedia.setObjectName("btnAddMedia")
        self.gridLayout_2.addWidget(self.btnAddMedia, 1, 0, 1, 1)
        self.btnRepeatPlayList = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnRepeatPlayList.setMaximumSize(QtCore.QSize(24, 24))
        self.btnRepeatPlayList.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playlist-repeat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRepeatPlayList.setIcon(icon10)
        self.btnRepeatPlayList.setObjectName("btnRepeatPlayList")
        self.gridLayout_2.addWidget(self.btnRepeatPlayList, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        self.lswPlayList = QtGui.QListWidget(self.dockWidgetContents_3)
        self.lswPlayList.setObjectName("lswPlayList")
        self.gridLayout_2.addWidget(self.lswPlayList, 0, 0, 1, 7)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OpenDev Player", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlayPause.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStop.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrevious.setShortcut(QtGui.QApplication.translate("MainWindow", "PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNext.setShortcut(QtGui.QApplication.translate("MainWindow", "PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFullscreen.setShortcut(QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVideoAspect.setItemText(0, QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVideoAspect.setItemText(1, QtGui.QApplication.translate("MainWindow", "Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTime.setText(QtGui.QApplication.translate("MainWindow", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShufflePlayList.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearPlayList.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveMedia.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddMedia.setShortcut(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRepeatPlayList.setShortcut(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))

from PySide import phonon
import icons_rc
