# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/devnix/dev/videoplayer/Qt/videoplayer.ui'
#
# Created: Thu Nov  1 03:04:54 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 567)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sldSeek = phonon.Phonon.SeekSlider(self.centralwidget)
        self.sldSeek.setEnabled(True)
        self.sldSeek.setMaximumSize(QtCore.QSize(16777215, 24))
        self.sldSeek.setMouseTracking(False)
        self.sldSeek.setObjectName("sldSeek")
        self.gridLayout.addWidget(self.sldSeek, 1, 5, 1, 1)
        self.btnStop = QtGui.QPushButton(self.centralwidget)
        self.btnStop.setMaximumSize(QtCore.QSize(24, 24))
        self.btnStop.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 1, 1, 1, 1)
        self.btnFullscreen = QtGui.QPushButton(self.centralwidget)
        self.btnFullscreen.setMaximumSize(QtCore.QSize(24, 24))
        self.btnFullscreen.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Buttons/icons/view-fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFullscreen.setIcon(icon1)
        self.btnFullscreen.setObjectName("btnFullscreen")
        self.gridLayout.addWidget(self.btnFullscreen, 1, 7, 1, 1)
        self.btnPrevious = QtGui.QPushButton(self.centralwidget)
        self.btnPrevious.setMaximumSize(QtCore.QSize(24, 24))
        self.btnPrevious.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-skip-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrevious.setIcon(icon2)
        self.btnPrevious.setObjectName("btnPrevious")
        self.gridLayout.addWidget(self.btnPrevious, 1, 2, 1, 1)
        self.btnPlayPause = QtGui.QPushButton(self.centralwidget)
        self.btnPlayPause.setMaximumSize(QtCore.QSize(24, 24))
        self.btnPlayPause.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playback-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnPlayPause.setIcon(icon3)
        self.btnPlayPause.setCheckable(True)
        self.btnPlayPause.setObjectName("btnPlayPause")
        self.gridLayout.addWidget(self.btnPlayPause, 1, 0, 1, 1)
        self.sldVolume = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.sldVolume.setMaximumSize(QtCore.QSize(100, 24))
        self.sldVolume.setObjectName("sldVolume")
        self.gridLayout.addWidget(self.sldVolume, 1, 4, 1, 1)
        self.cbxVideoAspect = QtGui.QComboBox(self.centralwidget)
        self.cbxVideoAspect.setMaximumSize(QtCore.QSize(16777215, 24))
        self.cbxVideoAspect.setObjectName("cbxVideoAspect")
        self.cbxVideoAspect.addItem("")
        self.cbxVideoAspect.addItem("")
        self.gridLayout.addWidget(self.cbxVideoAspect, 1, 8, 1, 1)
        self.btnAbout = QtGui.QPushButton(self.centralwidget)
        self.btnAbout.setMaximumSize(QtCore.QSize(24, 24))
        self.btnAbout.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Buttons/icons/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAbout.setIcon(icon4)
        self.btnAbout.setObjectName("btnAbout")
        self.gridLayout.addWidget(self.btnAbout, 1, 9, 1, 1)
        self.lblTime = QtGui.QLabel(self.centralwidget)
        self.lblTime.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lblTime.setTextFormat(QtCore.Qt.LogText)
        self.lblTime.setObjectName("lblTime")
        self.gridLayout.addWidget(self.lblTime, 1, 6, 1, 1)
        self.btnNext = QtGui.QPushButton(self.centralwidget)
        self.btnNext.setMaximumSize(QtCore.QSize(24, 24))
        self.btnNext.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-skip-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon5)
        self.btnNext.setObjectName("btnNext")
        self.gridLayout.addWidget(self.btnNext, 1, 3, 1, 1)
        self.vdpVideo = phonon.Phonon.VideoPlayer(self.centralwidget)
        self.vdpVideo.setObjectName("vdpVideo")
        self.gridLayout.addWidget(self.vdpVideo, 0, 0, 1, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_3.setEnabled(True)
        self.dockWidget_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dockWidget_3.setFloating(False)
        self.dockWidget_3.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnClearPlayList = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnClearPlayList.setMaximumSize(QtCore.QSize(24, 24))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Buttons/icons/edit-clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClearPlayList.setIcon(icon6)
        self.btnClearPlayList.setObjectName("btnClearPlayList")
        self.gridLayout_2.addWidget(self.btnClearPlayList, 1, 6, 1, 1)
        self.btnRemoveMedia = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnRemoveMedia.setMaximumSize(QtCore.QSize(24, 24))
        self.btnRemoveMedia.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Buttons/icons/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemoveMedia.setIcon(icon7)
        self.btnRemoveMedia.setObjectName("btnRemoveMedia")
        self.gridLayout_2.addWidget(self.btnRemoveMedia, 1, 5, 1, 1)
        self.lswPlayList = QtGui.QListWidget(self.dockWidgetContents_3)
        self.lswPlayList.setObjectName("lswPlayList")
        self.gridLayout_2.addWidget(self.lswPlayList, 0, 0, 1, 7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.btnAddMedia = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnAddMedia.setMaximumSize(QtCore.QSize(24, 24))
        self.btnAddMedia.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Buttons/icons/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddMedia.setIcon(icon8)
        self.btnAddMedia.setObjectName("btnAddMedia")
        self.gridLayout_2.addWidget(self.btnAddMedia, 1, 0, 1, 1)
        self.btnShufflePlayList = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnShufflePlayList.setMaximumSize(QtCore.QSize(24, 24))
        self.btnShufflePlayList.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playlist-shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShufflePlayList.setIcon(icon9)
        self.btnShufflePlayList.setObjectName("btnShufflePlayList")
        self.gridLayout_2.addWidget(self.btnShufflePlayList, 1, 2, 1, 1)
        self.btnRepeatPlayList = QtGui.QPushButton(self.dockWidgetContents_3)
        self.btnRepeatPlayList.setMaximumSize(QtCore.QSize(24, 24))
        self.btnRepeatPlayList.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Buttons/icons/media-playlist-repeat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRepeatPlayList.setIcon(icon10)
        self.btnRepeatPlayList.setObjectName("btnRepeatPlayList")
        self.gridLayout_2.addWidget(self.btnRepeatPlayList, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OpenDev Player", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStop.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFullscreen.setShortcut(QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrevious.setShortcut(QtGui.QApplication.translate("MainWindow", "PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlayPause.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVideoAspect.setItemText(0, QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVideoAspect.setItemText(1, QtGui.QApplication.translate("MainWindow", "Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTime.setText(QtGui.QApplication.translate("MainWindow", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNext.setShortcut(QtGui.QApplication.translate("MainWindow", "PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearPlayList.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveMedia.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddMedia.setShortcut(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShufflePlayList.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRepeatPlayList.setShortcut(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))

from PySide import phonon
import icons_rc
